name: Deploy Weather App to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # or your app's Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build project (optional)
      run: |
        if [ -f package.json ]; then
          npm run build || echo "No build script"
        fi

    - name: Deploy to Ubuntu Server via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /var/www/weather-app
          git pull origin main
          npm install
          pm2 restart weather-app || pm2 start npm --name "weather-app" -- start

